### ISSUE TITLE
Confusing arrows

### ISSUE THREAD

**Issue by jtojnar** [fizzyizzy05/binary#21]
The up/down arrows between the two number representations look like they should swap the two formats – they are of similar thickness to other clickable content – but clicking it does not do anything.

![The current window of Binary app, containing the arrows in the middle](https://github.com/user-attachments/assets/7b37a124-1e91-413e-bba7-abd60ed0ef50)

**Comment by fizzyizzy05** [comment]
This came up in the [GNOME Circle cross-review](https://gitlab.gnome.org/Teams/Circle/-/issues/233#note_2199839) too. Originally, it _was_ a swap button but it was removed with the redesign since the same functionality was provided by making the inputs mutable, and was retained as an image to help provide visual context. But it seems to be catching users out. 

I'm not sure whether it's better to replace it with e.g. text, make it a button again or remove it, but I'll definitely look at it a bit more.

**Comment by jtojnar** [comment]
Cool, I did not realize I can type to the lower entry as well.

I agree that greying out the arrows will signal that they are not clickable currently but it would still make me think there should be a way to make it active. I might expect it to become active after filling in a number and be slightly confused that it does not happen. I think the boldness of the arrows might by the affordance that is triggering this interpretation in me.

Perhaps we could just us regular `=` or `equals` labels.

This would also be useful for [fractional support](https://github.com/fizzyizzy05/binary/issues/22) where we could replace it with `≈` or `approximately equals` when the fraction could not be precisely finitely represented. Although it might be confusing as to which entry is the precise representation and which one is imprecise since `≈`, just like `=`, is symmetric.

**Comment by fizzyizzy05** [comment]
This is how it comes out as with just an equals sign: 
![image](https://github.com/user-attachments/assets/d451aa83-da37-42ac-9bdc-a42d5673d653)
I'm not 100% sure this is actually any better than having the arrows with the text to be honest. I feel the arrows indicate that changes work both ways and the text helps make it more how the app works, though I could possibly tweak it to be a bit more clear regarding knowing to type in the lower entry.

**Comment by jtojnar** [comment]
Right, while this no longer looks clickable, it being just a few pixels makes it feel like a noise. Adding a text might help but that would probably look even worse with the equal sign being off-centre. Maybe try using slightly thinner arrows or even ⇅ glyph?

As for the lower entry being editable, I guess I must have entered text into the upper one quickly so I never saw the placeholder. But I am not sure what affordances we could add that would not overly clutter the UI, other than perhaps making the entries less gray to make them look less disabledy :woman_shrugging:

**Comment by fizzyizzy05** [comment]
> Maybe try using slightly thinner arrows or even ⇅ glyph?

Possibly, but I'd like to stick to icons from the GNOME development kit to make things look and feel consistent, and even if I didn't I'm not sure that thinner icons would actually help here. The glyph kind of works, but I still prefer the arrows here and I'd be worried about it's affects on localisation.

> As for the lower entry being editable, I guess I must have entered text into the upper one quickly so I never saw the placeholder. But I am not sure what affordances we could add that would not overly clutter the UI, other than perhaps making the entries less gray to make them look less disabledy 🤷‍♀️

Yeah, Binary will immediately focus the first input when you start the app. I've considered using the card style for the entries, but otherwise I'm not sure what else could work, without custom styling the entries I'm not 100% sure about doing.
